### ISSUE TITLE
Problem with hashing and plots

### ISSUE THREAD

**Issue by blernermhc** [End-to-end-provenance/DDG-Explorer#102]
When I run the attached script and view the ddg in DDG Explorer, I get this error:
```
java.io.FileNotFoundException: /Users/blerner/Documents/Process/DataProvenance/Demos/BuggyCars/dev.off.11.pdf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at laser.ddg.AbstractDataInstanceNode.doFileHashing(AbstractDataInstanceNode.java:184)
	at laser.ddg.AbstractDataInstanceNode.<init>(AbstractDataInstanceNode.java:150)
	at laser.ddg.r.RDataInstanceNode.<init>(RDataInstanceNode.java:30)
	at laser.ddg.r.RDDGBuilder.addDataNode(RDDGBuilder.java:144)
	at laser.ddg.persist.Parser.addDataNode(Parser.java:273)
	at laser.ddg.persist.JSonParser.parseDataNodes(JSonParser.java:278)
	at laser.ddg.persist.JSonParser.parseNodesAndEdges(JSonParser.java:163)
	at laser.ddg.persist.Parser.addNodesAndEdges(Parser.java:154)
	at laser.ddg.commands.LoadFileCommand.loadFile(LoadFileCommand.java:61)
	at laser.ddg.gui.DDGExplorer.main(DDGExplorer.java:655)
```
The ddg has a dev.off.11.pdf node and when right-clicking on it, the expected plot appears.  It is reading this from the provenance data directory.

In the directory where the script lives, there is a file dev.off.10.pdf that contains the same graph.  I don't know why the file name is different, or what doFileHashing is trying to do when it reports this error

```
# Demonstrate using DDG to find bug.
# Graph has no data value for 8 cylinders
# Use ddg to find out what value mpg has.
# Then trace back to how it was calculated
# until you find in the bug (in the calculation
# of cars8Cyl.df).

# Load the mtcars data set that comes with R
data (mtcars)

# All the cars
allCars.df <- mtcars

# Create separate data frames for each number of cylinders
cars4Cyl.df <- allCars.df[allCars.df$cyl == 4, ]
cars6Cyl.df <- allCars.df[allCars.df$cyl == 6, ]
cars8Cyl.df <- allCars.df[cars6Cyl.df$cyl == 8, ]

# Create a table with the average mpg for each # cylinders
cylinders = c(4, 6, 8)
mpg = c(mean(cars4Cyl.df$mpg), mean(cars6Cyl.df$mpg), mean(cars8Cyl.df$mpg))
cyl.vs.mpg.df <- data.frame (cylinders, mpg)

# Plot it
plot(cylinders, mpg)
```

.

**Comment by blernermhc** [comment]
Fixed.
